// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrUHzpzLfQuH4E8KrgDicRcuXV2tD2BOk',
    appId: '1:897846234844:android:7cecd69a3044e4c3672e19',
    messagingSenderId: '897846234844',
    projectId: 'terzi-app',
    storageBucket: 'terzi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdK_wjPpTNI5BZ_yzkx074Nmr4TnsDl_M',
    appId: '1:897846234844:ios:cf166cd467af3bbb672e19',
    messagingSenderId: '897846234844',
    projectId: 'terzi-app',
    storageBucket: 'terzi-app.firebasestorage.app',
    iosBundleId: 'com.terziapp.terzi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdK_wjPpTNI5BZ_yzkx074Nmr4TnsDl_M',
    appId: '1:897846234844:ios:cf166cd467af3bbb672e19',
    messagingSenderId: '897846234844',
    projectId: 'terzi-app',
    storageBucket: 'terzi-app.firebasestorage.app',
    iosBundleId: 'com.terziapp.terzi',
  );
}
